### ISSUE TITLE
compile error :StateConstraint.h:48:29: error: enclosing class of constexpr non-static member function ‘ocs2::ConstraintOrder ocs2::StateConstraint::getOrder() const’ is not a literal type

### ISSUE THREAD

**Issue by dbdxnuliba** [leggedrobotics/ocs2#12]
/home/robot/ws_perceptive_mpc/src/ocs2/ocs2_core/include/ocs2_core/constraint/StateConstraint.h:48:29: error: enclosing class of constexpr non-static member function ‘ocs2::ConstraintOrder ocs2::StateConstraint::getOrder() const’ is not a literal type
I use cmake 3.14.7 in ubuntu16.04 kinetic environment

**Comment by tomlankhorst** [comment]
Hi @dbdxnuliba,

Please follow the provided bug report template. Also, group related compiler issues (#13, #14) in a single ticket. 

As described in the [prerequisites](https://leggedrobotics.github.io/ocs2/installation.html#prerequisites) section of the documentation, Ubuntu Xenial 16.04 does not satisfy the requirements. Please make sure your system satisfies the mentioned requirements. Consider running OCS2 in a container if you are not able to update your system.
