### ISSUE TITLE
compile err

### ISSUE THREAD

**Issue by dbdxnuliba** [leggedrobotics/ocs2#13]
/home/robot/ws_perceptive_mpc/src/ocs2/ocs2_core/src/integration/SensitivityIntegrator.cpp:76:75:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<ocs2::SensitivityIntegratorType>) (const ocs2::SensitivityIntegratorType&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>

I use cmake3.14.7 in ubuntu16.04 kinetic enviroment

**Comment by tomlankhorst** [comment]
See #12
