### ISSUE TITLE
compile err  ocs2/ocs2_pinocchio/ocs2_pinocchio_interface/src/PinocchioInterface.cpp:42:63:   required from here /usr/include/boost/variant/detail/make_variant_list.hpp:40:46: error: wrong number of template arguments (21, should be at least 0)

### ISSUE THREAD

**Issue by dbdxnuliba** [leggedrobotics/ocs2#14]
/home/robot/ws_perceptive_mpc/src/ocs2/ocs2_pinocchio/ocs2_pinocchio_interface/src/PinocchioInterface.cpp:42:63:   required from here
/usr/include/boost/variant/detail/make_variant_list.hpp:40:46: error: wrong number of template arguments (21, should be at least 0)
     typedef typename mpl::list< T... >::type type;

I use cmake3.14.7 in ubuntu16.04 kinetic and boost1.58

**Comment by tomlankhorst** [comment]
See #12

**Comment by dbdxnuliba** [comment]
thanks a lot ,I will try in ubuntu20.04
