### ISSUE TITLE
catkin package dependence issue

### ISSUE THREAD

**Issue by xwm-123** [leggedrobotics/ocs2#17]
When I'm compiling the package ocs2_legged_robot in ocs2_robotic_examples, the catkin needs package anymal_c_simple_description, but I couldn't find it anywhere

**Comment by farbod-farshidian** [comment]
Please also clone [the repository](https://github.com/ANYbotics/anymal_c_simple_description) to get ANymal urdf.

**Comment by xwm-123** [comment]
I think there is a missing line " include <atomic> " in file ocs2/ocs2_robotic_examples/ocs2_legged_robot/include/ocs2_legged_robot/gait/GaitReceiver.h.
You can check it
