### ISSUE TITLE
Why inequality constraint second derivative w.r.t. state or input need to be negative semi-definite?

### ISSUE THREAD

**Issue by matheecs** [leggedrobotics/ocs2#18]

**Comment by farbod-farshidian** [comment]
OCS2 assumes optimization problems with inequality constitution of type _h(x, u) >= 0_, and at each iteration of MPC, OCS2 uses the second-order approximation of this inequality constraint.
To find a solution for each sub-problem, the feasible set of the sub-problem should be a convex set. This is the case if the hessian of _h(x, u)_ is n.s.d.
As a simple example for a system with one state and one input: _x^2 + u^2 – 1 > 0_ is not a convex set but _-x^2 - u^2 + 1 > 0_ is a convex set.
