### ISSUE TITLE
build error no matching function for call

### ISSUE THREAD

**Issue by alme96** [leggedrobotics/ocs2#28]
**Describe the bug**
-Build error due to no matching function for call to from robot_state_publisher::RobotStatePublisher::publishFixedTransforms(bool)
-this error affects ocs2_ballbot_ros, ocs2_legged_robot and ocs2_mobile_manipulator_ros
- ocs2 and ocs2_robotic_examples are abandoned due to the failing of ocs2_ballbot_ros

**To Reproduce**
following the installation instructions form OCS2 documentation and also installed all the optional dependencies (pinocchio, raisim)
I needed to add "leggedrobotics/anymal_c_simple_description" to src

**Expected behavior**
successful building of ocs2

**Screenshots**
![Screenshot from 2021-12-16 13-20-47](https://user-images.githubusercontent.com/37303359/146371156-22b1b15e-5789-4d5d-8aa9-2c9031cc3726.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Browser: Mozilla Firefox 95.0

**Comment by rubengrandia** [comment]
This is an interface change in the ros package robot_state_publisher between Melodic and Noetic.
As written in the documentation, we currently only support Ubuntu 20.04 and its default ROS version (Noetic).

**Comment by wangarcher** [comment]
try to make a minor modification to the osc2 source code. 
change the corresponding line into:
`robotStatePublisherPtr_->publisherFixedTransforms("", true);`
to fit the melodic-devel robot_state_publisher package. 
I've tested it, and it worked without any problem.
