### ISSUE TITLE
Integration terminated since the maximum number of function calls is reached

### ISSUE THREAD

**Issue by xeonz1** [leggedrobotics/ocs2#32]
Hi,

On _Iteration 0_ of SLQ solver, I get an exception from the integrator (ODE45_OCS2):
> Integration terminated since the maximum number of function calls is reached. State at termination time -0.928457

I initialized the trajectory as 
```
    ocs2::SystemObservation initObservation;
    initObservation.state = interface.initialState;
    initObservation.input = ocs2::vector_t::Zero(robo::INPUT_DIM);
    initObservation.mode = 0;
    // Initial command
    ocs2::TargetTrajectories initTargetTrajectories(
        {0.0}, {initObservation.state}, {initObservation.input});

    // run dummy
    leggedRobotDummySimulator.run(initObservation, initTargetTrajectories);
```
and the mpc node as
```
    robo::RobotInterface interface(taskFilePath, targetTrajectoryFilePath);
    /*ros*/
    ros::init(argc, argv, interface.model.name);
    ros::NodeHandle nodeHandle;
    std::shared_ptr<ocs2::RosReferenceManager> rosReferenceManagerPtr(
        new ocs2::RosReferenceManager(interface.model.name, interface.refManager));
    rosReferenceManagerPtr->subscribe(nodeHandle);
    /*mpc*/
    ocs2::MPC_DDP mpc(interface.mpcSetting, interface.ddpSetting,
                      interface.rollout, interface.ocp, interface.initializer);
    mpc.getSolverPtr()->setReferenceManager(rosReferenceManagerPtr);
    ocs2::MPC_ROS_Interface mpcNode(mpc, interface.model.name);
    mpcNode.launchNodes(nodeHandle);
```
The starting time and initial state are defined in the `task.info` file. I think it is trying to run iteration on the initial trajectory but have no idea about why it comes to this exception. I wrote the code for dynamics built from pinocchio and CppAD instead of using the provided pinocchio interfaces.
**Update**
After debugging for a while I found the exception is raised when SLQ `integrateRiccatiEquationNominalTime` calls `integrateTimes`. 
**Update**
I tested the fullcentroidaldynamics version of the _leg

ged robot_ example, and soon it becomes unstable.
https://user-images.githubusercontent.com/56295370/152655845-19a45f25-f174-4710-b10a-bb3f68637009.mp4

**Comment by facontidavide** [comment]
We are having the same problem with a quadruped model... any advice?

**Comment by xeonz1** [comment]
> We are having the same problem with a quadruped model... any advice?

Sorry, but I am not on this already. Maybe its related to the stability of your dynamics/initialization or the constraints you added which has made the algorithm fails to produced stable solution.

**Comment by farbod-farshidian** [comment]
It seems that there has been an issue with the legged robot example. In the new release 10.1, this issue is resolved. Moreover, you will get up to 20% speedup.
