### ISSUE TITLE
Cannot fully track the base trajectory when standing

### ISSUE THREAD

**Issue by edward9503** [leggedrobotics/ocs2#37]
Dear OCS2 team,

I've found out that when the robot is standing, and we give a target distance of 0.5m forwards (as shown in the figure), the base trajectory (red curve) cannot be fully tracked. This won't happen when the robot is walking. So I was wondering if there is a bug for the stance case?
![ocs2](https://user-images.githubusercontent.com/39060488/171148091-d0601990-c422-4ec0-a509-1625c2650e10.png)

Best

**Comment by farbod-farshidian** [comment]
In the stance mode, the base displacement of 0.5m is impossible. The robot needs to take a step to stabilize. If you want to robustify the tracking for this situation, you probably should implement a similar method introduced in [this paper](https://arxiv.org/pdf/1703.02279.pdf).
