### ISSUE TITLE
External collision (obstacle) avoidance implementation

### ISSUE THREAD

**Issue by akmandor** [leggedrobotics/ocs2#39]
Is there any available (in ROS Noetic) obstacle avoidance implementation that I can run as an example? I know that [leggedrobotics/perceptive_mpc](https://github.com/leggedrobotics/perceptive_mpc) has that feature but it is not compiling in ROS Noetic and it seems like it is outdated after the recent updates on OCS2. I would appreciate if you can guide me on the implementation or point to any branch or repository that has the feature within the OCS2 framework.

**Comment by farbod-farshidian** [comment]
We plan to open-source the method we recently introduced in this [paper](https://www.research-collection.ethz.ch/handle/20.500.11850/534768). 

The self-collision pipeline is already available and used in the ocs2_mobile_manipulator examples. For environment avoidance, the automatic sphere decomposition of the robot is already online (ocs2_sphere_approximation). The missing parts are our interface to an SDF map and the function that defines a constraint based on this sphere approximation and the given SDF map.

**Comment by akmandor** [comment]
Have you released the code yet publicly?

**Comment by c-salmi** [comment]
Hi, I would also be interested in how to make ocs2_mobile_manipulator avoid collisions based on the sphere approximation of an SDF map.
