### ISSUE TITLE
Empty multiplier with preJumpStateEqualityLagrangian

### ISSUE THREAD

**Issue by xeonz1** [leggedrobotics/ocs2#48]
Version: 11.0
Code: 
```cpp
scalar_t MultidimensionalPenalty::getValue(scalar_t t, const vector_t& h, const vector_t* l) const {
  const auto numConstraints = h.rows();
  assert(penaltyPtrArray_.size() == 1 || penaltyPtrArray_.size() == numConstraints);

  scalar_t penalty = 0;
  for (size_t i = 0; i < numConstraints; i++) {
    const auto& penaltyTerm = (penaltyPtrArray_.size() == 1) ? penaltyPtrArray_[0] : penaltyPtrArray_[i];
    penalty += penaltyTerm->getValue(t, getMultiplier(l, i), h(i));
  }

  return penalty;
}
```
The `getMultiplier` triggered segmentation fault because `l` is an uninitialized empty vector. The problem occurs the first time the preJump constraint is active. The horizon is 1s, at 1s there is a mode switch, and the constraint is expected active at the switch.

```cpp
scalar_t getMultiplier(const vector_t* l, size_t ind) {
  return (l == nullptr) ? 0.0 : (*l)(ind);
}

```

**Comment by farbod-farshidian** [comment]
I added a unittest for the pre-jump and final time equality constraints (Tag 11.1). The unittest successfully passes. So I cannot replicate your issue. It will help if you create a minimal example such as this [unittest](https://github.com/leggedrobotics/ocs2/blob/main/ocs2_ddp/test/testReachingTask.cpp). I will close this issue for now.
