### ISSUE TITLE
Extremely slow execution of planned path after upgrade latest (Sep 30, 2022) packages

### ISSUE THREAD

**Issue by akmandor** [leggedrobotics/ocs2#52]
After I upgraded the packages on my system (Ubuntu 20.04, ROS Noetic) using `sudo apt upgrade`, the execution of the planned path visualized in Rviz by launching (I didn't test all, but probably all) robotic examples (such as Mabi-Mobile, Kinova Jaco2, Clearpath Ridgeback with UR-5) becomes extremely slow.

**Please note that:** 

1. Although before I was developing in separate branch; after I had this issue, I created another catkin workspace and installed the main branch and all necessary packages according to the [instructions](https://leggedrobotics.github.io/ocs2/installation.html). The issue I report here is based on the latest main branch on ocs2.
2. I also tested to run these examples in another computer without these upgrades (I was syncing two computers daily basis so the only differences between them are those upgrades) and there was no issue on that one.

Unfortunately, I could not narrow down which pkg upgrade(s) caused this, but I will include these packages below, hoping that you have a better insight on this weird issue.

Packages that I upgraded (automatically) today (Sep 30, 2022):

`google-chrome-stable=106.0.5249.61-1 firefox=104.0+build3-0ubuntu0.20.04.1 firefox-locale-en=104.0+build3-0ubuntu0.20.04.1 libsdformat9-dev:amd64=9.8.0-1~focal sdformat9-sdf=9.8.0-1~focal libsdformat9:amd64=9.8.0-1~focal ros-noetic-genmsg=0.5.16-1focal.20210423.222705 ros-noetic-genpy=0.6.15-1focal.20210423.222823 ros-noetic-message-runtime=0.4.13-1focal.20210423.222947 ros-noetic-gencpp=0.6.5-1focal.20210423.222749 ros-noetic-geneus=3.0.0-1focal.20210423.222918 ros-noetic-genlisp=0.4.18-1focal.20210423.222735 ros-noetic-gennodejs=2.0.2-1focal.20210423.222929 ros-noetic-message-generation=0.4.1-1focal.20210423.223101 ros-noetic-rosbuild=1.15.8-1focal.20210726.192137 ros-noetic-rosconsole=1.14.3-1focal.20210727.062322 ros-noetic-std-msgs=0.5.13-1focal.20210423.223321 ros-noetic-rosgraph-msgs=1.11.3-1focal.20210423.224118 ros-noetic-roscpp=1.15.14-1focal.20220106.233030 ros-noetic-hardware-interface=0.19.5-1focal.20220106.235702 ros-noetic-controller-interface=0.19.5-1focal.20220106.235928 ros-noetic-actionlib-msgs=1.13.1-1focal.20210423.225113 ros-noetic-geometry-msgs=1.13.1-1focal.20210423.223732 ros-noetic-trajectory-msgs=1.13.1-1focal.20210423.224726 ros-noetic-control-msgs=1.5.2-1focal.20210423.225159 ros-noetic-rospy=1.15.14-1focal.20220106.233657 ros-noetic-pluginlib=1.13.0-1focal.20210727.062753 ros-noetic-rosbag-storage=1.15.14-1focal.20220106.234146 ros-noetic-std-srvs=1.11.3-1focal.20210423.223330 ros-noetic-topic-tools=1.15.14-1focal.20220106.234130 ros-noetic-rosbag=1.15.14-1focal.20220106.234447 ros-noetic-rosmsg=1.15.14-1focal.20220106.234759 ros-noetic-rosservice=1.15.14-1focal.20220106.234935 ros-noetic-dynamic-reconfigure=1.7.3-1focal.20220519.084355 ros-noetic-nav-msgs=1.13.1-1focal.20210423.225233 ros-noetic-rosout=1.15.14-1focal.20220106.233651 ros-noetic-roslaunch=1.15.14-1focal.20220106.233833 ros-noetic-rostest=1.15.14-1focal.20220106.233954 ros-noetic-actionlib=1.13.2-1focal.20220106.235021 ros-noetic-realtime-tools=1.16.1-1focal.20220106.235327 ros-noetic-message-filters=1.15.14-1focal.20220106.234151 ros-noetic-rostopic=1.15.14-1focal.20220106.234801 ros-noetic-rosnode=1.15.14-1focal.20220106.234935 ros-noetic-roswtf=1.15.14-1focal.20220106.235010 ros-noetic-sensor-msgs=1.13.1-1focal.20220107.001034 ros-noetic-tf2-msgs=0.7.5-1focal.20210423.225302 ros-noetic-tf2=0.7.5-1focal.20210423.225547 ros-noetic-tf2-py=0.7.5-1focal.20220107.000244 ros-noetic-tf2-ros=0.7.5-1focal.20220107.000508 ros-noetic-tf=1.13.2-1focal.20220107.001704 ros-noetic-rosconsole-bridge=0.5.4-1focal.20210727.062632 ros-noetic-urdf=1.13.2-1focal.20220106.235206 ros-noetic-diff-drive-controller=0.20.0-1focal.20220519.091305 ros-noetic-ackermann-steering-controller=0.20.0-1focal.20220519.094919 ros-noetic-actionlib-tutorials=0.2.0-1focal.20220106.235301 ros-noetic-diagnostic-msgs=1.13.1-1focal.20210423.223644 ros-noetic-diagnostic-updater=1.11.0-1focal.20220106.234234 ros-noetic-amcl=1.17.2-1focal.20220621.180823 ros-noetic-async-web-server-cpp=1.0.3-1focal.20220107.000630 ros-noetic-audio-common-msgs=0.3.15-1focal.20220829.220605 ros-noetic-laser-geometry=1.6.7-1focal.20220107.002427 ros-noetic-map-msgs=1.14.1-1focal.20220107.004909 ros-noetic-visualization-msgs=1.13.1-1focal.20210423.224023 ros-noetic-voxel-grid=1.17.2-1focal.20220621.180435 ros-noetic-costmap-2d=1.17.2-1focal.20220621.180826 ros-noetic-nav-core=1.17.2-1focal.20220621.181513 ros-noetic-base-local-planner=1.17.2-1focal.20220621.181823 ros-noetic-bond=1.8.6-1focal.20210423.223553 ros-noetic-bondcpp=1.8.6-1focal.20220106.234115 ros-noetic-bondpy=1.8.6-1focal.20220107.000248 ros-noetic-bond-core=1.8.6-1focal.20220107.000920 ros-noetic-cv-bridge=1.16.1-1focal.20220906.152322 ros-noetic-image-geometry=1.16.1-1focal.20220906.152439 ros-noetic-camera-calibration=1.16.0-1focal.20220906.154018 ros-noetic-camera-calibration-parsers=1.12.0-1focal.20220107.001835 ros-noetic-image-transport=1.12.0-1focal.20220107.001857 ros-noetic-camera-info-manager=1.12.0-1focal.20220107.003151 ros-noetic-nodelet=1.10.2-1focal.20220106.234419 ros-noetic-capabilities=0.3.1-1focal.20220107.000455 ros-noetic-carrot-planner=1.17.2-1focal.20220621.182611 ros-noetic-resource-retriever=1.12.7-1focal.20211214.164815 ros-noetic-shape-msgs=1.13.1-1focal.20210423.224003 ros-noetic-geometric-shapes=0.7.3-1focal.20220514.015445 ros-noetic-urdfdom-py=0.4.6-1focal.20220107.000752 ros-noetic-srdfdom=0.6.3-1focal.20220201.004735 ros-noetic-kdl-parser=1.14.2-1focal.20220413.173353 ros-noetic-object-recognition-msgs=0.4.2-1focal.20220107.004954 ros-noetic-octomap-msgs=0.3.5-1focal.20210423.223941 ros-noetic-moveit-msgs=0.11.2-1focal.20220107.005220 ros-noetic-tf2-eigen=0.7.5-1focal.20210423.225948 ros-noetic-tf2-geometry-msgs=0.7.5-1focal.20220107.000842 ros-noetic-moveit-core=1.1.9-1focal.20220815.145341 ros-noetic-chomp-motion-planner=1.1.9-1focal.20220815.151800 ros-noetic-clear-costmap-recovery=1.17.2-1focal.20220621.181825 ros-noetic-stereo-msgs=1.13.1-1focal.20220107.005312 ros-noetic-common-msgs=1.13.1-1focal.20220107.010031 ros-noetic-nodelet-tutorial-math=0.2.0-1focal.20220106.234836 ros-noetic-pluginlib-tutorials=0.2.0-1focal.20220106.235108 ros-noetic-turtlesim=0.10.2-1focal.20220106.234424 ros-noetic-turtle-actionlib=0.2.0-1focal.20220106.235404 ros-noetic-common-tutorials=0.2.0-1focal.20220107.002300 ros-noetic-compressed-depth-image-transport=1.14.0-1focal.20220906.154115 ros-noetic-compressed-image-transport=1.14.0-1focal.20220906.153842 ros-noetic-control-toolbox=1.19.0-1focal.20220519.091120 ros-noetic-controller-manager-msgs=0.19.5-1focal.20220107.000302 ros-noetic-controller-manager=0.19.5-1focal.20220107.000501 ros-noetic-costmap-converter=0.0.13-1focal.20220906.152651 ros-noetic-ddynamic-reconfigure=0.3.2-1focal.20220519.092505 ros-noetic-eigen-conversions=1.13.2-1focal.20210423.223900 ros-noetic-depth-image-proc=1.16.0-1focal.20220906.153241 ros-noetic-turtle-tf=0.2.3-1focal.20220107.003050 ros-noetic-turtle-tf2=0.2.3-1focal.20220107.001151 ros-noetic-geometry-tutorials=0.2.3-1focal.20220107.011515 ros-noetic-joint-state-publisher=1.15.1-1focal.20220218.093002 ros-noetic-python-qt-binding=0.4.4-1focal.20210726.192424 ros-noetic-joint-state-publisher-gui=1.15.1-1focal.20220218.093511 ros-noetic-diagnostic-aggregator=1.11.0-1focal.20220107.000450 ros-noetic-diagnostic-analysis=1.11.0-1focal.20220107.000846 ros-noetic-diagnostic-common-diagnostics=1.11.0-1focal.20220107.003636 ros-noetic-self-test=1.11.0-1focal.20220106.234521 ros-noetic-diagnostics=1.11.0-1focal.20220107.003926 ros-noetic-smach-msgs=2.5.0-1focal.20210423.224149 ros-noetic-smach-ros=2.5.0-1focal.20220107.000235 ros-noetic-executive-smach=2.5.0-1focal.20220107.004327 ros-noetic-filters=1.9.2-1focal.20220512.124835 ros-noetic-kdl-conversions=1.13.2-1focal.20210423.223910 ros-noetic-tf-conversions=1.13.2-1focal.20220107.012308 ros-noetic-geometry=1.13.2-1focal.20220107.012748 ros-noetic-tf2-kdl=0.7.5-1focal.20220107.000843 ros-noetic-robot-state-publisher=1.15.2-1focal.20220413.174117 ros-noetic-nodelet-topic-tools=1.10.2-1focal.20220519.092216 ros-noetic-nodelet-core=1.10.2-1focal.20220519.095817 ros-noetic-mk=1.15.8-1focal.20210726.192420 ros-noetic-roslang=1.15.8-1focal.20210726.192150 ros-noetic-ros=1.15.8-1focal.20210727.062118 ros-noetic-roslisp=1.9.24-1focal.20210726.192430 ros-noetic-ros-comm=1.15.14-1focal.20220106.235155 ros-noetic-ros-core=1.5.0-1focal.20220107.010105 ros-noetic-ros-base=1.5.0-1focal.20220519.095901 ros-noetic-xacro=1.14.13-1focal.20220212.160007 ros-noetic-robot=1.5.0-1focal.20220519.102310 ros-noetic-roscpp-tutorials=0.10.2-1focal.20220106.235817 ros-noetic-rospy-tutorials=0.10.2-1focal.20220107.000622 ros-noetic-ros-tutorials=0.10.2-1focal.20220107.001106 ros-noetic-interactive-markers=1.12.0-1focal.20220107.001131 ros-noetic-rviz=1.14.19-1focal.20220815.135636 ros-noetic-urdf-tutorial=0.5.0-1focal.20220815.145010 ros-noetic-interactive-marker-tutorials=0.11.0-1focal.20220107.002345 ros-noetic-librviz-tutorial=0.11.0-1focal.20220815.144408 ros-noetic-rviz-plugin-tutorials=0.11.0-1focal.20220815.144706 ros-noetic-rviz-python-tutorial=0.11.0-1focal.20220815.144829 ros-noetic-visualization-marker-tutorials=0.11.0-1focal.20220106.234737 ros-noetic-visualization-tutorials=0.11.0-1focal.20220815.145402 ros-noetic-qt-gui=0.4.2-1focal.20210726.192753 ros-noetic-rqt-gui=0.5.3-1focal.20220328.224533 ros-noetic-rqt-gui-py=0.5.3-1focal.20220328.225040 ros-noetic-rqt-logger-level=0.4.11-1focal.20220328.225328 ros-noetic-rqt-py-common=0.5.3-1focal.20220328.224538 ros-noetic-rqt-console=0.4.11-1focal.20220328.225357 ros-noetic-rqt-msg=0.4.10-1focal.20220328.225436 ros-noetic-rqt-action=0.4.9-1focal.20220328.225504 ros-noetic-rqt-bag=0.5.1-1focal.20220328.225616 ros-noetic-qt-gui-py-common=0.4.2-1focal.20210726.192821 ros-noetic-rqt-plot=0.4.13-2focal.20220328.225111 ros-noetic-rqt-bag-plugins=0.5.1-1focal.20220328.225810 ros-noetic-qt-dotgraph=0.4.2-1focal.20210726.192724 ros-noetic-rqt-graph=0.4.14-1focal.20220328.225326 ros-noetic-rqt-dep=0.4.12-1focal.20220328.225604 ros-noetic-qt-gui-cpp=0.4.2-1focal.20210727.063105 ros-noetic-rqt-gui-cpp=0.5.3-1focal.20220328.224450 ros-noetic-rqt-image-view=0.4.16-1focal.20220906.153817 ros-noetic-rqt-launch=0.4.9-1focal.20220328.225434 ros-noetic-rqt-publisher=0.4.10-1focal.20220328.225218 ros-noetic-rqt-py-console=0.4.10-1focal.20220328.225605 ros-noetic-rqt-reconfigure=0.5.5-1focal.20220519.091134 ros-noetic-rqt-service-caller=0.4.10-1focal.20220328.225220 ros-noetic-rqt-shell=0.4.11-1focal.20220328.225349 ros-noetic-rqt-srv=0.4.9-1focal.20220328.225517 ros-noetic-rqt-top=0.4.10-1focal.20220328.225430 ros-noetic-rqt-topic=0.4.13-1focal.20220328.225437 ros-noetic-rqt-web=0.4.10-1focal.20220328.225602 ros-noetic-rqt-common-plugins=0.4.9-1focal.20220906.160735 ros-noetic-rqt-moveit=0.5.10-1focal.20220328.225504 ros-noetic-rqt-nav-view=0.5.7-1focal.20220328.225152 ros-noetic-rqt-pose-view=0.5.11-1focal.20220328.225119 ros-noetic-rqt-robot-monitor=0.5.14-1focal.20220328.225806 ros-noetic-rqt-robot-dashboard=0.5.8-1focal.20220328.225954 ros-noetic-rqt-robot-steering=0.5.12-1focal.20220328.225602 ros-noetic-rqt-runtime-monitor=0.5.9-1focal.20220328.225559 ros-noetic-rqt-rviz=0.7.0-1focal.20220815.144625 ros-noetic-rqt-tf-tree=0.6.3-1focal.20220331.120200 ros-noetic-rqt-robot-plugins=0.5.8-1focal.20220815.145413 ros-noetic-viz=1.5.0-1focal.20220906.161859 ros-noetic-desktop=1.5.0-1focal.20220906.162158 ros-noetic-polled-camera=1.12.0-1focal.20220107.003238 ros-noetic-image-common=1.12.0-1focal.20220107.012243 ros-noetic-image-proc=1.16.0-1focal.20220906.153713 ros-noetic-image-publisher=1.16.0-1focal.20220906.153738 ros-noetic-image-rotate=1.16.0-1focal.20220906.152658 ros-noetic-image-view=1.16.0-1focal.20220906.153859 ros-noetic-stereo-image-proc=1.16.0-1focal.20220906.154208 ros-noetic-image-pipeline=1.16.0-1focal.20220906.160026 ros-noetic-theora-image-transport=1.14.0-1focal.20220906.153933 ros-noetic-image-transport-plugins=1.14.0-1focal.20220906.160731 ros-noetic-laser-assembler=1.7.8-1focal.20220512.130035 ros-noetic-laser-filters=1.9.0-1focal.20220519.091721 ros-noetic-laser-pipeline=1.6.4-1focal.20220519.095620 ros-noetic-pcl-msgs=0.3.0-1focal.20220107.005305 ros-noetic-pcl-conversions=1.7.4-1focal.20220216.095102 ros-noetic-pcl-ros=1.7.4-1focal.20220520.061642 ros-noetic-perception-pcl=1.7.4-1focal.20220520.064711 ros-noetic-vision-opencv=1.16.1-1focal.20220906.153138 ros-noetic-perception=1.5.0-1focal.20220906.160811 ros-noetic-gazebo-msgs=2.9.2-1focal.20220107.005048 ros-noetic-gazebo-ros=2.9.2-1focal.20220519.091903 ros-noetic-gazebo-plugins=2.9.2-1focal.20220906.152700 ros-noetic-gazebo-ros-pkgs=2.9.2-1focal.20220906.161250 ros-noetic-stage-ros=1.8.0-1focal.20220107.003039 ros-noetic-simulators=1.5.0-1focal.20220906.161851 ros-noetic-joint-limits-interface=0.19.5-1focal.20220106.235926 ros-noetic-transmission-interface=0.19.5-1focal.20220106.235904 ros-noetic-gazebo-ros-control=2.9.2-1focal.20220519.094658 ros-noetic-joint-state-controller=0.20.0-1focal.20220512.124640 ros-noetic-forward-command-controller=0.20.0-1focal.20220512.124630 ros-noetic-position-controllers=0.20.0-1focal.20220512.124837 ros-noetic-urdf-sim-tutorial=0.5.1-1focal.20220815.145156 ros-noetic-desktop-full=1.5.0-1focal.20220906.162231 ros-noetic-dwa-local-planner=1.17.2-1focal.20220621.182243 ros-noetic-effort-controllers=0.20.0-1focal.20220519.094657 ros-noetic-fake-localization=1.17.2-1focal.20220621.180410 ros-noetic-force-torque-sensor-controller=0.20.0-1focal.20220512.124628 ros-noetic-franka-description=0.10.0-1focal.20220908.212816 ros-noetic-uuid-msgs=1.0.6-1focal.20210423.224434 ros-noetic-geographic-msgs=0.5.6-1focal.20210605.000032 ros-noetic-navfn=1.17.2-1focal.20220621.182116 ros-noetic-global-planner=1.17.2-1focal.20220621.182512 ros-noetic-gmapping=1.4.2-1focal.20220107.002506 ros-noetic-graph-msgs=0.1.0-2focal.20210423.223901 ros-noetic-grid-map-cv=1.6.4-1focal.20220906.154107 ros-noetic-grid-map-msgs=1.6.4-1focal.20220106.234334 ros-noetic-grid-map-ros=1.6.4-1focal.20220906.154457 ros-noetic-grid-map-rviz-plugin=1.6.4-1focal.20220906.160950 ros-noetic-gripper-action-controller=0.20.0-1focal.20220519.094627 ros-noetic-hector-map-tools=0.5.2-4focal.20210423.230125 ros-noetic-hector-compressed-map-transport=0.5.2-4focal.20220906.153759 ros-noetic-hector-gazebo-plugins=0.5.4-1focal.20220519.092542 ros-noetic-hector-nav-msgs=0.5.2-4focal.20210423.230130 ros-noetic-hector-geotiff=0.5.2-4focal.20220106.233828 ros-noetic-hector-geotiff-plugins=0.5.2-4focal.20220107.000855 ros-noetic-hector-trajectory-server=0.5.2-4focal.20220107.002646 ros-noetic-hector-geotiff-launch=0.5.2-4focal.20220107.003903 ros-noetic-hector-imu-attitude-to-tf=0.5.2-4focal.20220107.002542 ros-noetic-hector-marker-drawing=0.5.2-4focal.20220106.234436 ros-noetic-hector-map-server=0.5.2-4focal.20220107.002618 ros-noetic-hector-mapping=0.5.2-4focal.20220107.002900 ros-noetic-hector-slam-launch=0.5.2-4focal.20220815.144625 ros-noetic-hector-slam=0.5.2-4focal.20220906.160751 ros-noetic-hls-lfcd-lds-driver=1.1.2-1focal.20220107.001841 ros-noetic-hpp-fcl=2.1.2-1focal.20220912.181902 ros-noetic-imu-filter-madgwick=1.2.5-1focal.20220823.164534 ros-noetic-imu-sensor-controller=0.20.0-1focal.20220512.125128 ros-noetic-tf2-sensor-msgs=0.7.5-1focal.20220107.002056 ros-noetic-imu-transformer=0.3.0-2focal.20220107.002340 ros-noetic-interactive-marker-twist-server=1.2.2-1focal.20220107.002353 ros-noetic-joint-trajectory-controller=0.20.0-1focal.20220519.094643 ros-noetic-joy=1.15.1-1focal.20220107.001731 ros-noetic-teleop-tools-msgs=0.4.0-1focal.20210423.225515 ros-noetic-joy-teleop=0.4.0-1focal.20220107.002043 ros-noetic-jsk-footstep-msgs=4.3.2-1focal.20210423.225200 ros-noetic-jsk-recognition-msgs=1.2.15-1focal.20220107.005530 ros-noetic-laser-ortho-projector=0.3.3-1focal.20220520.063804 ros-noetic-laser-scan-matcher=0.3.3-1focal.20220520.064608 ros-noetic-laser-scan-sparsifier=0.3.3-1focal.20220107.001631 ros-noetic-laser-scan-splitter=0.3.3-1focal.20220107.001646 ros-noetic-libmavconn=1.13.0-1focal.20220810.202815 ros-noetic-lms1xx=0.3.0-2focal.20220107.001900 ros-noetic-map-server=1.17.2-1focal.20220621.180409 ros-noetic-mavros-msgs=1.13.0-1focal.20220113.084554 ros-noetic-mavros=1.13.0-1focal.20220810.203123 ros-noetic-mbf-abstract-core=0.4.0-1focal.20211026.191919 ros-noetic-mbf-utility=0.4.0-1focal.20220107.002405 ros-noetic-mbf-costmap-core=0.4.0-1focal.20220621.181831 ros-noetic-mbf-msgs=0.4.0-1focal.20211026.191913 ros-noetic-microstrain-3dmgx2-imu=1.5.13-1focal.20220107.002715 ros-noetic-move-base-msgs=1.14.1-1focal.20210423.225212 ros-noetic-rotate-recovery=1.17.2-1focal.20220621.182615 ros-noetic-move-base=1.17.2-1focal.20220621.183020 ros-noetic-move-slow-and-clear=1.17.2-1focal.20220621.182127 ros-noetic-moveit-ros-occupancy-map-monitor=1.1.9-1focal.20220815.151800 ros-noetic-moveit-ros-planning=1.1.9-1focal.20220815.152032 ros-noetic-warehouse-ros=0.9.5-1focal.20220510.081837 ros-noetic-moveit-ros-warehouse=1.1.9-1focal.20220815.153512 ros-noetic-moveit-kinematics=1.1.9-1focal.20220815.154002 ros-noetic-moveit-ros-move-group=1.1.9-1focal.20220815.154251 ros-noetic-moveit-ros-manipulation=1.1.9-1focal.20220815.155527 ros-noetic-moveit-ros-planning-interface=1.1.9-1focal.20220912.182033 ros-noetic-moveit-commander=1.1.9-1focal.20220912.182958 ros-noetic-moveit-planners-chomp=1.1.9-1focal.20220912.183113 ros-noetic-moveit-planners-ompl=1.1.9-1focal.20220815.154137 ros-noetic-pilz-industrial-motion-planner=1.1.9-1focal.20220912.183628 ros-noetic-moveit-planners=1.1.9-1focal.20220912.184813 ros-noetic-moveit-fake-controller-manager=1.1.9-1focal.20220815.153741 ros-noetic-moveit-simple-controller-manager=1.1.9-1focal.20220815.151800 ros-noetic-moveit-ros-control-interface=1.1.9-1focal.20220815.152436 ros-noetic-moveit-plugins=1.1.9-1focal.20220815.154010 ros-noetic-moveit-ros-benchmarks=1.1.9-1focal.20220815.154415 ros-noetic-moveit-ros-perception=1.1.9-1focal.20220906.152649 ros-noetic-moveit-ros-robot-interaction=1.1.9-1focal.20220815.153511 ros-noetic-moveit-ros-visualization=1.1.9-1focal.20220912.183000 ros-noetic-moveit-ros=1.1.9-1focal.20220912.184702 ros-noetic-moveit-setup-assistant=1.1.9-1focal.20220912.184642 ros-noetic-moveit=1.1.9-1focal.20220912.185737 ros-noetic-navigation=1.17.2-1focal.20220621.183641 ros-noetic-ncd-parser=0.3.3-1focal.20220107.002746 ros-noetic-nmea-msgs=1.1.0-1focal.20210423.223822 ros-noetic-nmea-comms=1.2.0-3focal.20220106.234629 ros-noetic-nmea-navsat-driver=0.6.1-2focal.20220107.003644 ros-noetic-octomap-ros=0.4.1-1focal.20220514.015020 ros-noetic-pinocchio=2.6.9-2focal.20220912.185923 ros-noetic-pointcloud-to-laserscan=1.4.1-1focal.20220107.002833 ros-noetic-pointgrey-camera-description=0.15.1-1focal.20220413.175145 ros-noetic-polar-scan-matcher=0.3.3-1focal.20220107.003005 ros-noetic-realsense2-camera=2.3.2-1focal.20220906.153355 ros-noetic-realsense2-description=2.3.2-1focal.20220212.161322 ros-noetic-rgbd-launch=2.3.0-1focal.20220906.160418 ros-noetic-robot-localization=2.7.4-1focal.20220729.124845 ros-noetic-robot-pose-ekf=1.15.0-2focal.20220107.003015 ros-noetic-robot-self-filter=0.1.32-1focal.20220520.064643 ros-noetic-robot-upstart=0.4.2-1focal.20220217.090727 ros-noetic-velocity-controllers=0.20.0-1focal.20220519.094749 ros-noetic-ros-controllers=0.20.0-1focal.20220519.095236 ros-noetic-ros-numpy=0.0.5-2focal.20220107.003648 ros-noetic-rosbridge-library=0.11.14-1focal.20220615.161520 ros-noetic-rosapi=0.11.14-1focal.20220615.161853 ros-noetic-rosauth=1.0.1-1focal.20220106.234716 ros-noetic-rosbridge-msgs=0.11.14-1focal.20220615.161535 ros-noetic-rosbridge-server=0.11.14-1focal.20220615.161932 ros-noetic-rosdoc-lite=0.2.10-1focal.20210423.222829 ros-noetic-rosparam-shortcuts=0.4.0-1focal.20220106.234044 ros-noetic-rospy-message-converter=0.5.9-1focal.20220912.175101 ros-noetic-rosserial-msgs=0.9.2-1focal.20210423.223234 ros-noetic-rosserial-python=0.9.2-1focal.20220107.000351 ros-noetic-variant-msgs=0.1.6-1focal.20210423.224434 ros-noetic-variant-topic-tools=0.1.6-1focal.20220106.234434 ros-noetic-rqt-multiplot=0.0.12-1focal.20220328.224855 ros-noetic-rviz-imu-plugin=1.2.5-1focal.20220823.164227 ros-noetic-rviz-visual-tools=3.9.1-1focal.20220815.145126 ros-noetic-scan-to-cloud-converter=0.3.3-1focal.20220520.064730 ros-noetic-scan-tools=0.3.3-1focal.20220520.065501 ros-noetic-sick-tim=0.0.17-1focal.20220519.091711 ros-noetic-smach-viewer=4.0.1-1focal.20220906.152653 ros-noetic-sound-play=0.3.15-1focal.20220829.221132 ros-noetic-spacenav-node=1.15.1-1focal.20220107.001953 ros-noetic-teb-local-planner=0.9.1-1focal.20220906.160038 ros-noetic-teleop-twist-joy=0.1.3-1focal.20220107.002011 ros-noetic-teleop-twist-keyboard=1.0.0-1focal.20220107.000515 ros-noetic-tf2-tools=0.7.5-1focal.20220107.004507 ros-noetic-tf2-web-republisher=0.3.2-3focal.20220107.002444 ros-noetic-turtlebot3-msgs=1.0.1-1focal.20210423.224157 ros-noetic-twist-mux-msgs=2.1.0-1focal.20220107.004036 ros-noetic-twist-mux=3.1.2-1focal.20220819.064426 ros-noetic-velodyne-description=1.0.12-2focal.20220212.161113 ros-noetic-velodyne-gazebo-plugins=1.0.12-2focal.20220519.100106 ros-noetic-web-video-server=0.2.2-1focal.20220906.154245`

**Comment by fp018** [comment]
Hi Akamandor,

I am facing the same issue, I created ad Docker image following the ocs2 instructions but even simple examples are very slow and give "WARNING: The solution time window might be shorter than the MPC delay". 

The base immage I used is: osrf/ros:noetic-desktop-full 

I did not check all the packages but I have:

ros-noetic-rqt-multiplot = 0.0.12-1focal.20220926.212043
ros-noetic-grid-map-msgs = Installed: 1.6.4-1focal.20220926.185630
ros-noetic-grid-map-rviz-plugin = : 1.6.4-1focal.20221003.144531

Have you managed to solve the problem in the meantime? 

Thanks

**Comment by akmandor** [comment]
Hi @fp018,

Unfortunately, I could not solve the issue and, instead, using my other computer which wasn't updated.

I suspect the issue is related with the Pinocchio update but I haven't had time to neither confirm nor fix that.

**Comment by akmandor** [comment]
Although, I have been doing some assessments to understand what causes this issue, I still haven't been not able to fix it yet. Below, I tried to summarize these assessments. 

I really appreciate any feedback or solution for the issue that I had reported. As I said, although I can continue to work on my computer which wasn't updated, this issue will probably cause more troubles in terms of other possible package updates that we cannot avoid while maintaining our system. This issue also prevents us to use the library on a new system with Ubuntu 20.04 + ROS Noetic.

Assessment 1: 
To narrow down which specific functions causing the issue, I added timers around function calls and compared their duration for three computers (one of them without and two of them with above Ubuntu updates) with similar CPU.

I tried to focus on functions which causes significance computation time difference between two case (with and without updates). Based on my observations, especially if the function uses Pinocchio library (such as forward kinematics) the difference is more significant. However, when I checked the version of package and even its dependencies, all of them are using the same version (please check the Assessment 2 for more details)! At this point, I could not go deeper into the actual function implementations for further assessment...

Assessment 2: 
I checked all ROS package dependecies of the "ocs2_mobile_manipulator_ros":
`rospack depends ocs2_mobile_manipulator_ros`

The output was:
```
[rospack] Error: package 'pinocchio' depends on non-existent package 'ament_cmake' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
[rospack] Error: package 'hpp-fcl' depends on non-existent package 'liboctomap-dev' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
[rospack] Error: package 'hpp-fcl' depends on non-existent package 'libassimp-dev' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
[rospack] Error: package 'pinocchio' depends on non-existent package 'ament_cmake' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
[rospack] Error: package 'pinocchio' depends on non-existent package 'ament_cmake' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
[rospack] Error: package 'pinocchio' depends on non-existent package 'ament_cmake' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
catkin
ros_environment
rospack
... (Omitted but you can find the rest below)
```

One by one, I checked versions using `rosversion` command in 3 computers (1 without and 2 with updates) and they all have the same version packages (which is super weird for me) such as:
```
catkin 0.8.10
ros_environment 1.3.2
rospack 2.6.2
roslib 1.15.8
cpp_common 0.7.2
rostime 0.7.2
roscpp_traits 0.7.2
roscpp_serialization 0.7.2
genmsg 0.5.16
genpy 0.6.15
message_runtime 0.4.13
std_msgs 0.5.13
geometry_msgs 1.13.1
gencpp 0.6.5
geneus 3.0.0
gennodejs 2.0.2
genlisp 0.4.18
message_generation 0.4.1
rosbuild 1.15.8
rosconsole 1.14.3
rosgraph_msgs 1.11.3
xmlrpcpp 1.15.14
roscpp 1.15.14
message_filters 1.15.14
rosgraph 1.15.14
rosclean 1.15.8
rosmaster 1.15.14
rosout 1.15.14
rosparam 1.15.14
rosunit 1.15.8
roslaunch 1.15.14
rospy 1.15.14
topic_tools 1.15.14
pluginlib 1.13.0
roslz4 1.15.14
rosbag_storage 1.15.14
std_srvs 1.11.3
rosbag 1.15.14
rostopic 1.15.14
rosnode 1.15.14
rosmsg 1.15.14
rosservice 1.15.14
roswtf 1.15.14
sensor_msgs 1.13.1
actionlib_msgs 1.13.1
rostest 1.15.14
actionlib 1.13.2
tf2_msgs 0.7.5
tf2 0.7.5
tf2_py 0.7.5
tf2_ros 0.7.5
tf 1.13.2
rosconsole_bridge 0.5.4
urdf 1.13.2
kdl_parser 1.14.2
tf2_kdl 0.7.5
robot_state_publisher 1.15.2
visualization_msgs 1.13.1
ocs2_thirdparty 0.0.1
ocs2_core 0.0.0
ocs2_oc 0.0.0
ocs2_qp_solver 0.0.0
ocs2_mpc 0.0.0
ocs2_ddp 0.0.0
ocs2_robotic_tools 0.0.0
ocs2_robotic_assets 10.3.0
python_qt_binding 0.4.4
qt_gui 0.4.2
rqt_gui 0.5.3
qt_gui_cpp 0.4.2
bond 1.8.6
smclib 1.8.6
bondcpp 1.8.6
nodelet 1.10.2
rqt_gui_cpp 0.5.3
variant_msgs 0.1.6
variant_topic_tools 0.1.6
rqt_multiplot 0.0.12
ocs2_msgs 0.0.0
tf2_geometry_msgs 0.7.5
interactive_markers 1.12.0
ocs2_ros_interfaces 0.0.0
octomap 1.9.8
hpp-fcl 1.6.0
pinocchio 2.5.1
ocs2_pinocchio_interface 0.0.0
ocs2_self_collision 0.0.0
ocs2_self_collision_visualization 0.0.0
ocs2_mobile_manipulator 0.0.0
```

**Comment by fp018** [comment]
Hi @akmandor,

I solved the issue (maybe it is not the same problem) using: `catkin config -DCMAKE_BUILD_TYPE=Release` instead of 
`catkin config -DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Comment by akmandor** [comment]
Thank you so much @fp018 !!!
