### ISSUE TITLE
Boost version

### ISSUE THREAD

**Issue by scharalambous3** [leggedrobotics/ocs2#6]
Hi,

I believe the listed dependency in the documentation should be

> Boost C++ (v1.71)

instead of 

> Boost C++ (v1.54)

(or otherwise it leads to errors such as as boost/core/null_deleter.hpp missing)

Setup: Ubunty 20.04, ros noetic

Thanks!
Stefanos

**Comment by tomlankhorst** [comment]
Thanks for pointing this out
