### ISSUE TITLE
ocs2_legged_robot "ddp" and "sqp" example bug

### ISSUE THREAD

**Issue by rcjhhsh** [leggedrobotics/ocs2#74]
**Describe the bug**
An error was reported while running `roslaunch ocs2_legged_robot_ros legged_robot_ddp.launch` and `roslaunch ocs2_legged_robot_ros legged_robot_sqp.launch`

**Screenshots**
![Screenshot from 2023-05-10 17-50-11](https://github.com/leggedrobotics/ocs2/assets/52849484/ecd3e232-393d-4742-b545-3aa8e88c7535)

![Screenshot from 2023-05-10 17-51-45](https://github.com/leggedrobotics/ocs2/assets/52849484/1351386e-b31b-4ef0-b64b-fa1afefc99ce)

![Screenshot from 2023-05-10 17-48-32](https://github.com/leggedrobotics/ocs2/assets/52849484/01f504a6-5882-411b-85e1-a5ce63203033)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 20.04

**Additional context**
Pinocchio and Hpp-fcl are installed by conda -c conda-forge
All of the examples your provided can work except legged robot example
The "sqp" example problem is same as "ddp"

**Comment by rcjhhsh** [comment]
> Perhaps you are using different versions of CppAd

I check my CppAD version. My CppAD just use the ocs2_thirdparty‘s cppad. and the version is:
CPPAD version:
repository: https://github.com/coin-or/CppAD/tree/stable/20190200
tag: 20190200.5
commit_hash: 6d82707ef4847d4cb3bf27a4671918ee618512fd

**Comment by YifeiLyu** [comment]
Hi, can I ask how did you fix this issue?
