### ISSUE TITLE
ocs2_robotic_tools folder location

### ISSUE THREAD

**Issue by rightcore** [leggedrobotics/ocs2#8]
Thanks for the nice library.
However, when I catkin build, the message "....            src/ocs2/ocs2_robotic_examples/ocs2_robotic_tools does not exist." is shown. 
Please move the folder  "src/ocs2/ocs2_robotic_tools" to src/ocs2/ocs2_robotic_examples/ocs2_robotic_tools.

**Comment by farbod-farshidian** [comment]
Either clean your workspace and build again or do $ catkin build --force-cmake <package-name>
