### ISSUE TITLE
Perceptive Anymal Instructions

### ISSUE THREAD

**Issue by lucasbrodo** [leggedrobotics/ocs2#86]
Hi,

I was wondering if you would provide instructions on how to use ocs2_perceptive_anymal (e.g ocs2_anymal_loopshaping_mpc demo script). It looks like I'm missing some packages when trying to build the package (like grid_map_filters_rsl, etc).

Thanks for your information.

Lucas

**Comment by rubengrandia** [comment]
grid_map_filters_rsl is part of https://github.com/leggedrobotics/elevation_mapping_cupy
