### ISSUE TITLE
friction cone rotation matrix

### ISSUE THREAD

**Issue by graiola** [leggedrobotics/ocs2#88]
Hi, first I would like to thank you for this amazing framework. I have a question, is it possible to change the rotation matrix in the friction cone constraint? I have been trying to change the matrix online but it looks like I can not access the constraint object inside the solver. Thank you in advance.

**Comment by IoannisDadiotis** [comment]
Hi Gennaro,

As a user of the library I would say one possible way to go can be similar to `NormalVelocityConstraintCppAd` in the legged robot example. You can take a look in the lines below:
https://github.com/leggedrobotics/ocs2/blob/164c26b46bed5d24cd03d90588db8980d03a4951/ocs2_robotic_examples/ocs2_legged_robot/src/constraint/NormalVelocityConstraintCppAd.cpp#L68-L69
This constraint is configured by accessing member variables of the `LeggedRobotPreComputation` object, which are updated in [LeggedRobotPreComputation::request](https://github.com/leggedrobotics/ocs2/blob/164c26b46bed5d24cd03d90588db8980d03a4951/ocs2_robotic_examples/ocs2_legged_robot/src/LeggedRobotPreComputation.cpp#L65). Maybe you could do something similar for the friction cone constraint.
